apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-secrets-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: fastapi-secrets 
    creationPolicy: Owner
  data:
    - secretKey: API_SECRET_KEY
      remoteRef:
        key: API-SECRET-KEY

    - secretKey: AUTH_AUDIENCE
      remoteRef:
        key: AUTH-AUDIENCE

    - secretKey: AUTH_CLIENT_ID
      remoteRef:
        key: AUTH-CLIENT-ID

    - secretKey: AUTH_CLIENT_SECRET
      remoteRef:
        key: AUTH-CLIENT-SECRET

    - secretKey: AUTH_DOMAIN
      remoteRef:
        key: AUTH-DOMAIN

    - secretKey: CHECKING_ACCOUNT_NR
      remoteRef:
        key: CHECKING-ACCOUNT-NR

    - secretKey: SPAREKONTO_18_23_ACCOUNT_NR
      remoteRef: 
        key: SPAREKONTO-18-23-ACCOUNT-NR

    - secretKey: BSU_ACCOUNT_NR
      remoteRef: 
        key: BSU-ACCOUNT-NR
