apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: johannes
  namespace: flux-system
spec:
  interval: 10m                     # how often Flux should reconcile
  path: ./clusters/raspberry-pi/johannes_api  # relative path from repo root to eso folder
  prune: true                      # cleans up removed resources
  sourceRef:
    kind: GitRepository
    name: flux-system 
